// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUVUEkSOqL-Y1nMySk4mS9GoxMGI2JLUw',
    appId: '1:557437267074:web:af687de6fe65b88c59589b',
    messagingSenderId: '557437267074',
    projectId: 'flash-chat-81360',
    authDomain: 'flash-chat-81360.firebaseapp.com',
    storageBucket: 'flash-chat-81360.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc-aakfdmR5syqGGbL7WbZFTw4R0Fjzco',
    appId: '1:557437267074:android:dcba7d864517e0ea59589b',
    messagingSenderId: '557437267074',
    projectId: 'flash-chat-81360',
    storageBucket: 'flash-chat-81360.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO-mZbrXSUhVdAESak81yU8Wmq1FsbQVA',
    appId: '1:557437267074:ios:ab80b466c738123159589b',
    messagingSenderId: '557437267074',
    projectId: 'flash-chat-81360',
    storageBucket: 'flash-chat-81360.appspot.com',
    iosBundleId: 'com.example.flash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO-mZbrXSUhVdAESak81yU8Wmq1FsbQVA',
    appId: '1:557437267074:ios:e2efbe548b4a2e2459589b',
    messagingSenderId: '557437267074',
    projectId: 'flash-chat-81360',
    storageBucket: 'flash-chat-81360.appspot.com',
    iosBundleId: 'com.example.flash.RunnerTests',
  );
}
